main:
  - name: Home
    url: "/"
    weight: 10
  - name: Über Uns
    url: "/ueber/"
    weight: 20
  - name: News
    url: "/news/"
    weight: 30
  - name: Einsätze
    url: "/mission/"
    weight: 40
  - name: Extern
    url: "/company/"
    weight: 50
  - name: Kontakt
    url: "/contact-us/"
    params:
      class: "button"
    weight: 60
  - name: Lodur
    parent: "Extern"
    url: "https://lodur-zh.ch/urdorf/"
    weight: 10
  - name: Feuerwehr Cloud
    parent: "Extern"
    url: "https://files.feuerwehrurdorf.ch/"
    weight: 20
  - name: GVZ
    parent: "Extern"
    url: "https://www.gvz.ch/hauptnavigation/feuerwehr"
    weight: 30
  - name: FKS CSSP CSP / Feukos
    parent: "Extern"
    url: "https://www.feukos.ch/"
    weight: 40

footer_left:
  - name: Home
    url: "/"
    weight: 10
  - name: Über Uns
    url: "ueber"
    weight: 20
  - name: News
    url: "news"
    weight: 30
  - name: Einsätze
    url: "mission"
    weight: 40

footer_center:
  - name: Impressum
    url: "impressum"
    weight: 10
